export const HTTP_READ = 'GET';
export const HTTP_CREATE = 'POST';
export const HTTP_UPDATE = 'PUT';
export const HTTP_DELETE = 'DELETE';
export const LIMIT = 10;

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const GET_DETAIL_USER_REQUEST = 'GET_DETAIL_USER_REQUEST';
export const GET_DETAIL_USER_SUCCESS = 'GET_DETAIL_USER_SUCCESS';
export const GET_DETAIL_USER_FAILURE = 'GET_DETAIL_USER_FAILURE';

export const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAILURE = 'GET_CATEGORY_FAILURE';

export const GET_DETAIL_CATEGORY_REQUEST = 'GET_DETAIL_CATEGORY_REQUEST';
export const GET_DETAIL_CATEGORY_SUCCESS = 'GET_DETAIL_CATEGORY_SUCCESS';
export const GET_DETAIL_CATEGORY_FAILURE = 'GET_DETAIL_CATEGORY_FAILURE';

export const ADD_CATEGORY_REQUEST = 'ADD_CATEGORY_REQUEST';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';

export const UPDATE_CATEGORY_REQUEST = 'UPDATE_CATEGORY_REQUEST';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAILURE = 'UPDATE_CATEGORY_FAILURE';

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE';

export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';

export const actionDetailProduct = {
  GET_PRODUCT_DETAIL_REQUEST: 'GET_PRODUCT_DETAIL_REQUEST',
  GET_PRODUCT_DETAIL_SUCCESS: 'GET_PRODUCT_DETAIL_SUCCESS',
  GET_PRODUCT_DETAIL_FAILURE: 'GET_PRODUCT_DETAIL_FAILURE',
};
export const actionsMedia = {
  GET_IMG_MEDIA_REQUEST: ' GET_IMG_MEDIA_REQUEST',
  GET_IMG_MEDIA_SUCCESS: ' GET_IMG_MEDIA_SUCCESS',
  GET_IMG_MEDIA_FAILURE: ' GET_IMG_MEDIA_FAILURE',

  GET_DETAIL_IMG_MEDIA_REQUEST: ' GET_DETAIL_IMG_MEDIA_REQUEST',
  GET_DETAIL_IMG_MEDIA_SUCCESS: ' GET_DETAIL_IMG_MEDIA_SUCCESS',
  GET_DETAIL_IMG_MEDIA_FAILURE: ' GET_DETAIL_IMG_MEDIA_FAILURE',

  ADD_IMG_MEDIA_REQUEST: ' ADD_IMG_MEDIA_REQUEST',
  ADD_IMG_MEDIA_SUCCESS: ' ADD_IMG_MEDIA_SUCCESS',
  ADD_IMG_MEDIA_FAILURE: ' ADD_IMG_MEDIA_FAILURE',

  UPDATE_IMG_MEDIA_REQUEST: ' UPDATE_IMG_MEDIA_REQUEST',
  UPDATE_IMG_MEDIA_SUCCESS: ' UPDATE_IMG_MEDIA_SUCCESS',
  UPDATE_IMG_MEDIA_FAILURE: ' UPDATE_IMG_MEDIA_FAILURE',

  DELETE_IMG_MEDIA_REQUEST: ' DELETE_IMG_MEDIA_REQUEST',
  DELETE_IMG_MEDIA_SUCCESS: ' DELETE_IMG_MEDIA_SUCCESS',
  DELETE_IMG_MEDIA_FAILURE: ' DELETE_IMG_MEDIA_FAILURE',
};
export const actionsBill = {
  GET_BILLS_REQUEST: ' GET_BILLS_REQUEST',
  GET_BILLS_SUCCESS: ' GET_BILLS_SUCCESS',
  GET_BILLS_FAILURE: ' GET_BILLS_FAILURE',

  GET_DETAIL_BILL_REQUEST: ' GET_DETAIL_BILL_REQUEST',
  GET_DETAIL_BILL_SUCCESS: ' GET_DETAIL_BILL_SUCCESS',
  GET_DETAIL_BILL_FAILURE: ' GET_DETAIL_BILL_FAILURE',

  ADD_BILL_REQUEST: ' ADD_BILL_REQUEST',
  ADD_BILL_SUCCESS: ' ADD_BILL_SUCCESS',
  ADD_BILL_FAILURE: ' ADD_BILL_FAILURE',

  UPDATE_BILL_REQUEST: ' UPDATE_BILL_REQUEST',
  UPDATE_BILL_SUCCESS: ' UPDATE_BILL_SUCCESS',
  UPDATE_BILL_FAILURE: ' UPDATE_BILL_FAILURE',

  DELETE_BILL_REQUEST: ' DELETE_BILL_REQUEST',
  DELETE_BILL_SUCCESS: ' DELETE_BILL_SUCCESS',
  DELETE_BILL_FAILURE: ' DELETE_BILL_FAILURE',
};
export const actionsNews = {
  GET_NEWS_REQUEST: ' GET_NEWS_REQUEST',
  GET_NEWS_SUCCESS: ' GET_NEWS_SUCCESS',
  GET_NEWS_FAILURE: ' GET_NEWS_FAILURE',

  GET_DETAIL_NEWS_REQUEST: ' GET_DETAIL_NEWS_REQUEST',
  GET_DETAIL_NEWS_SUCCESS: ' GET_DETAIL_NEWS_SUCCESS',
  GET_DETAIL_NEWS_FAILURE: ' GET_DETAIL_NEWS_FAILURE',

  ADD_NEWS_REQUEST: ' ADD_NEWS_REQUEST',
  ADD_NEWS_SUCCESS: ' ADD_NEWS_SUCCESS',
  ADD_NEWS_FAILURE: ' ADD_NEWS_FAILURE',

  UPDATE_NEWS_REQUEST: ' UPDATE_NEWS_REQUEST',
  UPDATE_NEWS_SUCCESS: ' UPDATE_NEWS_SUCCESS',
  UPDATE_NEWS_FAILURE: ' UPDATE_NEWS_FAILURE',

  DELETE_NEWS_REQUEST: ' DELETE_NEWS_REQUEST',
  DELETE_NEWS_SUCCESS: ' DELETE_NEWS_SUCCESS',
  DELETE_NEWS_FAILURE: ' DELETE_NEWS_FAILURE',
};

export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE';

export const ADD_IMAGE_REQUEST = 'ADD_IMAGE_REQUEST';
export const ADD_IMAGE_SUCCESS = 'ADD_IMAGE_SUCCESS';
export const ADD_IMAGE_FAILURE = 'ADD_IMAGE_FAILURE';

export const DELETE_IMAGE_REQUEST = 'DELETE_IMAGE_REQUEST';
export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS';
export const DELETE_IMAGE_FAILURE = 'DELETE_IMAGE_FAILURE';

